import "../app/style/globals.css";
import SideBar from "./components/shared/ASide/SideBar";
import Navbar from "./components/shared/Navbar/Navbar";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Symun",
};

export default function RootLayout({ children }) {
  return (
    <div className="pt-[50px] pb-20 w-full h-screen bg-cover bg-no-repeat">
      <Navbar />
      <div className="container_fluid">
        <div className="flex justify-start items-start">
          <SideBar />
          <main>{children}</main>
        </div>
      </div>
    </div>
  );
}
